test_fmetis – Fortran METIS Interface
test_fmetis Program
36 statements
Source File
Uses:
iso_c_binding
metis_interface
metis_enum
metis_io
Calls
Variables
mgraph xadj adjncy part options ios ncon objval
Variables
Type Attributes Name Initial
type(MetisGraph) :: mgraph
integer, allocatable :: xadj(:)
integer, allocatable :: adjncy(:)
integer, allocatable :: part(:)
integer(kind=c_int) :: options(40)
integer(kind=c_int) :: ios
integer(kind=c_int) :: ncon
integer(kind=c_int) :: objval
All Programs
test_fmetis test_NodeND test_PartGraphKway test_PartGraphRecursive1 test_PartGraphRecursive2 test_PartMeshNodal1 test_PartMeshNodal2
Call graph
test_fmetis calls metis_setdefaultoptions, test1, test4, test2, metis_partgraphkway, test3, write_graph, load_graph
load_graph calls whitechar, count_columns
count_columns calls whitechar