import_graph – Fortran METIS Interface
import_graph Subroutine
13 statements
Source File
public subroutine import_graph(fname, graph, numflag)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: fname
class(graph_type), intent(out) :: graph
integer, intent(in), optional :: numflag
Calls
All Procedures
count_columns count_columns export_graph ForMETIS_MeshToNodal import_graph load_graph METIS_Free METIS_MeshToDual METIS_MeshToNodal METIS_NodeND METIS_PartGraphKway METIS_PartGraphRecursive METIS_PartMeshDual METIS_PartMeshNodal METIS_SetDefaultOptions print_metis_options read_graph whitechar whitechar write_graph write_graph
Call graph
import_graph calls read_graph
read_graph calls whitechar, count_columns
count_columns calls whitechar