load_graph – Fortran METIS Interface
load_graph Subroutine
162 statements
Source File
public subroutine load_graph(this, fname, numflag)
Arguments
Type Intent Optional Attributes Name
type(MetisGraph), intent(out) :: this
character(len=*), intent(in) :: fname
integer, intent(in) :: numflag
Calls
Called By
All Procedures
count_columns ForMETIS_MeshToNodal load_graph METIS_Free METIS_MeshToDual METIS_MeshToNodal METIS_NodeND METIS_PartGraphKway METIS_PartGraphRecursive METIS_PartMeshDual METIS_PartMeshNodal METIS_SetDefaultOptions print_options test1 test2 test3 test4 whitechar write_graph
Call graph
load_graph calls whitechar, count_columns
count_columns calls whitechar
test_fmetis calls load_graph