test1 – Fortran METIS Interface
test1 Subroutine
34 statements
Source File
public subroutine test1()
Uses:
iso_c_binding
Arguments
None
Calls
All Procedures
count_columns ForMETIS_MeshToNodal load_graph METIS_Free METIS_MeshToDual METIS_MeshToNodal METIS_NodeND METIS_PartGraphKway METIS_PartGraphRecursive METIS_PartMeshDual METIS_PartMeshNodal METIS_SetDefaultOptions print_options test1 test2 test3 test4 whitechar write_graph
Call graph
test1 calls metis_meshtonodal, metis_setdefaultoptions, metis_partmeshnodal, formetis_meshtonodal, write_graph, metis_free
formetis_meshtonodal calls metis_meshtonodal, metis_free